### PR TITLE
Angular 17 Upgrade

### PR DESCRIPTION
**Pull request by rcorry93**
Created a PR based off an already open Angular 16 Upgrade. Continued to upgrade it to Angular 17.

Please leave any feedback.

### CODE REVIEW

**Comment by rcorry93** [comment]
@ramandeep-singh-1983 Let me know if there's anything more i can help with on this PR

**Comment by ramandeep-singh-1983** [comment]
Sorry for the delay, had to reset my GitHub password so it took some time. I have approved the PR, can you ensure that it's properly tested and then merge it?

**Review by ramandeep-singh-1983 — APPROVED** [review]

**Comment by rcorry93** [comment]
Working for my Angular 17 project and cant seem to find any issues with it.

**Comment by rcorry93** [comment]
@ramandeep-singh-1983 I don't have 'write access' so I am unable to merge it.

**Comment by rcorry93** [comment]
@ramandeep-singh-1983 Could you merge this if you are happy with the PR, I can't merge.

**Comment by ramandeep-singh-1983** [comment]
Merged it, will try to create npm package and push to npmjs in some time.

**Comment by drazafsky** [comment]
> Merged it, will try to create npm package and push to npmjs in some time.

Any update on when a new npmjs package will be available?

**Comment by rcorry93** [comment]
Any update on an npm package and push being completed?

**Pull request merged**
